CREATE TABLE [dbo].[Users] (
    [Id]         INT            IDENTITY (1, 1) NOT NULL,
    [GivenName]  NVARCHAR (255) NOT NULL,
    [FamilyName] NVARCHAR (255) NOT NULL,
    [Email] NVARCHAR (255) NOT NULL,
    [Phone] NVARCHAR (255) NOT NULL DEFAULT(''),
    [Created] DATETIME NOT NULL DEFAULT GETDATE(),
    [Modified] DATETIME NOT NULL DEFAULT GETDATE(),
    [Password] NVARCHAR (MAX) NOT NULL,
    CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED ([Id] ASC)
);

